
  $(document).ready(function(){
    $('#typewriteText').typewrite({
        continuous: false,
        actions: [
            {type: 'Studio réalité is a space where we express our creativity aside from our main jobs. '},
            {type: '<br>'},
            {delay: 1000},
            {type: 'We use this sapce to archi'},
            {delay: 1000},
            {speed: 18},
            {select: {from: 99, to: 104}},
            {delay: 1000},
            {remove: {num: 14, type: 'stepped'}},
            {delay: 1000},
            {type: 'space to archive our little everyday objects. '},
            {type: '<br>'},
            {speed: 12},
            {type: 'This is where we express, try to grab our réalité and bring it to the universe.'},
            {type: '<br>'},
            {delay: 500},
            {type: '<br>'},
            {speed: 18},
            {type: 'The name is from the 60s french magazine called : Réalité. '},
            {type: 'The edition of this magazine was an archive of that time. '},
            {type: 'It bring us back to this time where we did not exist. '},
            {type: '<br>'},
            {delay: 1000},
            {type: '<br>'},
            {speed: 10},
            {type: 'We thought about doing the same thing with our everyday life that will build an archive of our réalité. '},
            {type: 'It start from us but we hope to grow with everyone that want to bring too some '},
            {delay: 1000},
            {type: 'réalité.'},
            {type: '<br>'},
            {delay: 1000},
            {type: '<br>'},
            {speed: 15},
            {type: 'We will consider to archive things that fits into those 3 fundamentals : '},
            {delay: 1200},
            {speed: 12},
            {type: 'created or collaborated by one of us, a product and inspired by the context of life at that time.'},
            {type: '<br>'},
            {type: '<br>'},
            {delay: 1500},
            {speed: 5},
            {type: 'That is a product of Studio réalité.'},
            {select: {from: 804, to: 818}}
        ]
    });
  });