---
label: Products
hide_body: true
fields:
- type: field_group_list
  name: Products
  label: Products
  fields:
  - type: text
    name: id
    label: id
    config:
      required: true
  - type: text
    name: name
    label: name
    config:
      required: true
  - type: number
    name: price
    label: price
    config:
      required: true
      min: '0'
  - type: file
    name: image
    label: image
    config:
      maxSize: '15'
  - type: text
    name: description
    label: description
    config:
      required: true
  - name: product_url
    type: select
    default: []
    config:
      required: true
      options: []
      source:
        type: pages
        section: portfolio
        file: 
        path: 
    label: product_url
pages:
- data/products.json
